### ISSUE TITLE
Could we have an update for 1.19.3 please?

### ISSUE THREAD

**Issue by bentterp** [LostQuasar/FabricSecretRooms#20]
`---- Minecraft Crash Report ---- // There are four lights! Time: 2022-12-11 05:26:56 Description: Initializing game java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'secretrooms'! 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:465) 	at net.minecraft.client.main.Main.method_44604(Main.java:205) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) 	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2571 		at com.terraformersmc.terrestria.init.TerrestriaBlocks.init(TerrestriaBlocks.java:111) 		at com.terraformersmc.terrestria.Terrestria.register(Terrestria.java:31) 		at com.terraformersmc.terrestria.Terrestria.onInitialize(Terrestria.java:56) 		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 		... 17 more 	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2571 		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) 		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) 		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 		... 21 more Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1792$class_1793 net.minecraft.class_1792$class_1793.method_7892(net.minecraft.class_1761)' 	at com.github.spaceman.SecretRooms.<clinit>(SecretRooms.java:33) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 	... 17 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:465)`

**Comment by LostQuasar** [comment]
Please use pastebin for crash reports
